postgre_common_config: &postgre_common_config
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  host: localhost

development:
  database: bigc_development
  <<: *postgre_common_config
test:
  database: bigc_test
  <<: *postgre_common_config
production:
  database: bigc_production
  <<: *postgre_common_config
